---
name: "Build"
"on":
- "push"
jobs:
  compile-and-test:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout sources"
      uses: "actions/checkout@v4"
    - name: "Setup sdkman"
      run: "curl -s \"https://get.sdkman.io?rcupdate=false\" | bash"
    - name: "Setup project sdk"
      run: "sdk env install"
    - name: "Gradle build"
      run: "./gradlew clean build"
    - name: "Gradle collect coverage report"
      run: "./gradlew testCodeCoverageReport"
    - name: "Archive code coverage report"
      uses: "actions/upload-artifact@v4"
      with:
        name: "code-coverage-report"
        path: "build/reports/jacoco/*"
