---
name: "Build"
"on":
- "push"
jobs:
  compile:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout sources"
      uses: "actions/checkout@v4"
    - name: "Gradle build (skip tests)"
      run: "./gradlew build -x test"
    - name: "Gradle unit tests"
      run: "./gradlew test"
    - name: "Gradle collect coverage report"
      run: "./gradlew testCodeCoverageReport"
